### PR TITLE
feat: emit SetGasprice event in MgvOracle

### LINKED ISSUE #250: MgvOracle should emit events to allow tracking state off chain
**Is your feature request related to a problem? Please describe.**
The `MgvOracle` should emit events that allow off-chain monitoring of state changes regarding gas and density.

**Describe the solution you'd like**
* For the gasprice, the `MgvOracle` must emit `SetGasprice(uint)` whenever gasprice is updated.

**Additional context**
Similarly, in the future, `MgvOracle` should emit events for density-updates (the oracle does not control `density`, right now), by emitting a similarly named event whenever the density is updated. See #377 concerning `MgvOracle` and `density`.

This has ties with our monitoring solutions.

### PR DESCRIPTION
**Pull request by dontrolle**
Fixes #250

### CODE REVIEW

**Comment by adhusson** [comment]
I had written a comment but it somehow never got posted! So was saying : looks good to me, I think let's do it all at once and add all events here + split commits by concern (core contract change, tests, syntax prettification)

**Review by adhusson — COMMENTED** [review]
see comments [there](https://github.com/mangrovedao/mangrove/issues/250)

**Comment by dontrolle** [comment]
Marking this as draft. I'm going to make another PR to keep the commit history easily reviewable (as per comments).

**Comment by dontrolle** [comment]
To keep the commit-history clean, this PR https://github.com/mangrovedao/mangrove/pull/391 subsumes this one. I'll close this one.

**Pull request closed without merging**
