### PR TITLE
feat(mangrove.js): generalize volume estimations (#620)

### LINKED ISSUE #620: mangrove.js: Add price limit in volume estimation
Per @johanleroch, mangrove.js could use a volume estimation that includes an average price limit.

### PR DESCRIPTION
**Pull request by adhusson**
Closes #620.

Summary: mangrove.js now faithfully simulates mangrove's solidity execution engine. The `estimateVolume` function has been changed and includes a new `boundary` parameter.

If `params.to == buy`, then the mapping to solidity code is:
* `params.given` --> `takerWants`
* `params.boundary` --> `takerGives`

Otherwise if `params.to == sell`, then the mapping is:
* `params.given` --> `takerGives`
* `params.boundary` --> `takerWants`

You can omit the `estimateVolume`'s `boundary` param and use it like before. It will automatically set a very high max avg. price when buying, and a 0 min avg. price when selling.

### CODE REVIEW

**Comment by johanleroch** [comment]
should it also change something for the functions estimateVolumeToSpend and estimateVolumeToReceive?

**Comment by adhusson** [comment]
> should it also change something for the functions estimateVolumeToSpend and estimateVolumeToReceive?

good catch, I just checked and thanks to good type layout those functions got implicitly updated (they now have a new `boundary` parameters field available).

**Comment by johanleroch** [comment]
> > should it also change something for the functions estimateVolumeToSpend and estimateVolumeToReceive?
> 
> good catch, I just checked and thanks to good type layout those functions got implicitly updated (they now have a new `boundary` parameters field available).

Nice, good job so :)

**Review by jkrivine — APPROVED** [review]
Looks all good to me

**Pull request merged**
